### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Ronal1999** [Overwrite987/UltimateServerProtector#35]
[17:09:31 WARN]: [UltimateServerProtector] Entity task for UltimateServerProtector v29.0 generated an exception
java.lang.IllegalArgumentException: effect type cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:85) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:56) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:106) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:119) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:131) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at ru.overwrite.protect.bukkit.ServerProtectorManager.lambda$giveEffect$3(ServerProtectorManager.java:301) ~[UltimateServerProtector-en.jar:?]
        at ru.overwrite.protect.bukkit.task.PaperRunner.lambda$toConsumer$0(PaperRunner.java:65) ~[UltimateServerProtector-en.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:168) ~[purpur-1.20.2.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:115) ~[purpur-1.20.2.jar:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.lambda$tickChildren$13(MinecraftServer.java:1508) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1501) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2094]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by Ronal1999** [comment]
I updated to the newest veersion

**Comment by Overwrite987** [comment]
> I updated to the newest veersion

Can you actually read the error please?

**Comment by Ronal1999** [comment]
nop

**Comment by Overwrite987** [comment]
> nop

then just reset your config.yml and be happy
