### ISSUE TITLE
error when using ultimateserverprotection plugin

### ISSUE THREAD

**Issue by Elabrax** [Overwrite987/UltimateServerProtector#36]
[23:50:16 WARN] [UltimateServerProtector]: Plugin UltimateServerProtector v29.0 generated an exception while executing task 1677
java.lang.NoSuchMethodError: 'boolean ru.overwrite.protect.bukkit.api.ServerProtectorCaptureEvent.callEvent()'
        at ru.overwrite.protect.bukkit.listeners.ConnectionListener.lambda$onLogin$0(ConnectionListener.java:57) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23208!/:arclight-1.20.1-1.0.5-1a8925b]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23208!/:arclight-1.20.1-1.0.5-1a8925b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?] 
        
        When I try to use one of the commands nothing appears, it's as if the server loaded a blank file but the folder I loaded I don't know if you can help me with this problem

**Comment by Overwrite987** [comment]
> [23:50:16 WARN] [UltimateServerProtector]: Plugin UltimateServerProtector v29.0 generated an exception while executing task 1677 java.lang.NoSuchMethodError: 'boolean ru.overwrite.protect.bukkit.api.ServerProtectorCaptureEvent.callEvent()' at ru.overwrite.protect.bukkit.listeners.ConnectionListener.lambda$onLogin$0(ConnectionListener.java:57) ~[?:?] at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23208!/:arclight-1.20.1-1.0.5-1a8925b] at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23208!/:arclight-1.20.1-1.0.5-1a8925b] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?] at java.lang.Thread.run(Thread.java:842) ~[?:?]
> 
> ```
>     When I try to use one of the commands nothing appears, it's as if the server loaded a blank file but the folder I loaded I don't know if you can help me with this problem
> ```

And this is the reason why you should NEVER use server software that suppot bukkit plugins and forge mods.
This is not a plugin issue.
