### ISSUE TITLE
Можешь выпустить обновление для версии 1.21?

### ISSUE THREAD

**Issue by TheFaik** [Overwrite987/UltimateServerProtector#38]
Пожалуйста, обнови плагин для 1.21 или ты ждёшь Stable-
версию Paper?

```
[ModernPluginLoadingStrategy] Could not load plugin 'UltimateServerProtector.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: Exception initializing main class `ru.overwrite.protect.bukkit.ServerProtector'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:106) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[purpur-1.21.jar:1.21-2245-9efd5fc]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.21.jar:1.21-2245-9efd5fc]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.21.jar:1.21-2245-9efd5fc]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.21.jar:1.21-2245-9efd5fc]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[purpur-1.21.jar:1.21-2245-9efd5fc]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:549) ~[purpur-1.21.jar:1.21-2245-9efd5fc]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[purpur-1.21.jar:1.21-2245-9efd5fc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[purpur-1.21.jar:1.21-2245-9efd5fc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2245-9efd5fc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.ExceptionInInitializerError
        at UltimateServerProtector.jar/ru.overwrite.protect.bukkit.ServerProtectorManager.<init>(ServerProtectorManager.java:40) ~[UltimateServerProtector.jar:?]
        at UltimateServerProtector.jar/ru.overwrite.protect.bukkit.ServerProtector.<init>(ServerProtector.java:13) ~[UltimateServerProtector.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.NumberFormatException: For input string: "21-R0"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.base/java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
        at java.base/java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
        at UltimateServerProtector.jar/ru.overwrite.protect.bukkit.utils.Utils.<clinit>(Utils.java:33) ~[UltimateServerProtector.jar:?]
        at UltimateServerProtector.jar/ru.overwrite.protect.bukkit.ServerProtectorManager.<init>(ServerProtectorManager.java:40) ~[UltimateServerProtector.jar:?]
        at UltimateServerProtector.jar/ru.overwrite.protect.bukkit.ServerProtector.<init>(ServerProtector.java:13) ~[UltimateServerProtector.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        ... 10 more
```

**Comment by Overwrite987** [comment]
Я жду удаления ремаппера из пейпера
