### ISSUE TITLE
UltimateServerProtector wont start

### ISSUE THREAD

**Issue by Gabkill54** [Overwrite987/UltimateServerProtector#40]
Hello,
i have this error on paper 1.12
Can you help me ?

My plugin : 
AutoShutdown
DiscordSRV-Build-1.27.0
DiscordSRVUtils-1.2.14-BETA-1
Dynmap-3.7-beta-6-spigot
SkinsRestorer
TAB v4.1.6
UltimateServerProtector-en

```[23:07:01 INFO]: Enabling UltimateServerProtector v31.0
[23:07:01 ERROR]: Error occurred while enabling UltimateServerProtector v31.0 (Is it up to date?)
java.lang.NullPointerException: null
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?]
	at UltimateServerProtector-en.jar/ru.overwrite.protect.bukkit.utils.Config.setupPasswords(Config.java:74) ~[UltimateServerProtector-en.jar:?]
	at UltimateServerProtector-en.jar/ru.overwrite.protect.bukkit.ServerProtectorManager.loadConfigs(ServerProtectorManager.java:137) ~[UltimateServerProtector-en.jar:?]
	at UltimateServerProtector-en.jar/ru.overwrite.protect.bukkit.ServerProtector.onEnable(ServerProtector.java:23) ~[UltimateServerProtector-en.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-109-5a5035b]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-109-5a5035b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-109-5a5035b]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-109-5a5035b]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-109-5a5035b]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-109-5a5035b]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-109-5a5035b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-109-5a5035b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-109-5a5035b]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:07:01 INFO]: Disabling UltimateServerProtector v31.0```

**Comment by Gabkill54** [comment]
My plugin configuration crash UltimateServerProtector °_°

**Comment by Gabkill54** [comment]
my configuration is great but the plugin not kick other ip, i have correctly configured plugin

**Comment by Gabkill54** [comment]
i have activated ip whitelist
its not working
plugin not bloque ip

**Comment by Overwrite987** [comment]
> my configuration is great but the plugin not kick other ip, i have correctly configured plugin

you didn't
