### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheFaik** [Overwrite987/UltimateServerProtector#5]
```
[14:30:05 WARN]: Unexpected exception while parsing console command "usp"
org.bukkit.command.CommandException: Cannot execute command 'usp' in plugin UltimateServerProtector v17.5 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:975) ~[purpur-1.19.3.jar:git-Purpur-1900]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:938) ~[purpur-1.19.3.jar:git-Purpur-1900]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:536) ~[purpur-1.19.3.jar:git-Purpur-1900]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[purpur-1.19.3.jar:git-Purpur-1900]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1900]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1900]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1900]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by Overwrite987** [comment]
Plugin is disabled.
I need error on startup

**Comment by Overwrite987** [comment]
> ```
> [14:30:05 WARN]: Unexpected exception while parsing console command "usp"
> org.bukkit.command.CommandException: Cannot execute command 'usp' in plugin UltimateServerProtector v17.5 - plugin is disabled.
>         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:975) ~[purpur-1.19.3.jar:git-Purpur-1900]
>         at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:938) ~[purpur-1.19.3.jar:git-Purpur-1900]
>         at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:536) ~[purpur-1.19.3.jar:git-Purpur-1900]
>         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[purpur-1.19.3.jar:git-Purpur-1900]
>         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1900]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1900]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1900]
>         at java.lang.Thread.run(Thread.java:1589) ~[?:?]
> ```

so... should I wait for an error when enabling the plugin?
